spring.application.name=qrCodeGeneratorApi
# Nome do banco em memória
spring.datasource.url=jdbc:h2:mem:testdb

# Driver do H2
spring.datasource.driver-class-name=org.h2.Driver

# Usuário e senha (padrão do H2)
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialeto do Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativar console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
